# Generated by Django 3.2.12 on 2022-07-23 10:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0006_profilemodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfileModel',
            new_name='ProfileModels',
        ),
    ]
